
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306//core
#    username: rooot
#    password: prabhakar
#  jpa:
#    hibernate:
#      auto-ddl:update
#    show-sql: true
#server:
#  port: 8080

